version: '3'
services:
  react:
    container_name: movie-library-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3300:3300
    environment:
      - CHOKIDAR_USEPOLLING=true
